### ISSUE TITLE
"go get github.com/hyperledger/fabric-sdk-go" doesn't working

### ISSUE THREAD

**Issue by lotty02cho** [hyperledger-labs/blockchain-analyzer#13]
I try to run this project by following README.md.

but when I start to run Beats Agent, I saw that kind of below issue.

```
go get -u github.com/hyperledger/fabric-sdk-go
go get: warning: modules disabled by GO111MODULE=auto in GOPATH/src;
	ignoring go.mod;
	see 'go help modules'
```

Does anyone that kind of issue? I guess it is related to golang or absolute path... but I don't know.

**Comment by balazsprehoda** [comment]
I think it is related to go modules not working under $GOPATH, I am going to check. Meanwhile, you could try to simply clone the [fabric-sdk-go github repository](https://github.com/hyperledger/fabric-sdk-go) and place it under $GOPATH/src/github.com, then run this project. The warning won't disappear, but I think it will run fine.

**Comment by salmanbaset** [comment]
I am getting similar issue. The modules need fixing. Try the solution that @balazsprehoda suggested or getting vendor modules from this old commit:
https://github.com/hyperledger-labs/blockchain-analyzer/tree/14199bfa3e770822a7877652d1a589b425b94894/agent/fabricbeat/vendor/github.com

**Comment by balazsprehoda** [comment]
Placing the fabric-sdk-go package inside vendor dir in fabricbeat should resolve the problem. However, it is going to break the dumper program.

**Comment by salmanbaset** [comment]
@lotty02cho for now, the `fabric-sdk-go` has been included in the repo. See instructions here on building the agent:
https://github.com/hyperledger-labs/blockchain-analyzer/blob/master/docs/Basic_setup.md#build-fabricbeat-agent

**Comment by balazsprehoda** [comment]
Since this issue is outdated, I am closing it now.
