### ISSUE TITLE
fabricbeat: make causing issue "undefined: idtools.Identity"

### ISSUE THREAD

**Issue by saurabhdatopic** [hyperledger-labs/blockchain-analyzer#22]
$GOPATH/src/github.com/blockchain-analyzer/agent/fabricbeat/vendor/github.com/elastic/beats/libbeat/scripts/Makefile
go build -i -ldflags "-X $GOPATH/src/github.com/blockchain-analyzer/agent/fabricbeat/vendor/github.com/elastic/beats/libbeat/version.buildTime=2019-09-26T21:23:34Z -X $GOPATH/src/github.com/blockchain-analyzer/agent/fabricbeat/vendor/github.com/elastic/beats/libbeat/version.commit=74ec2c73aedc79dc6349696d342a6afa8064164e"
#github.com/fsouza/go-dockerclient/internal/archive
../../../../../pkg/mod/github.com/fsouza/go-dockerclient@v1.4.4/internal/archive/archive.go:73:19: **undefined: idtools.Identity**
$GOPATH/src/github.com/blockchain-analyzer/agent/fabricbeat/vendor/github.com/elastic/beats/libbeat/scripts/Makefile:107: recipe for target 'fabricbeat' failed
make: *** [fabricbeat] Error 2

Any help would be highly appreciated.

**Comment by saurabhdatopic** [comment]
for me, Go version 1.12.4 resolved it.

**Comment by balazsprehoda** [comment]
I am glad you figured it out.
